image: mcr.microsoft.com/dotnet/core/sdk:3.0.100

stages:
    - test
    - deploy
    - documentation

release:
    stage: deploy
    only:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - ./*.nupkg
    script:
        - ./build.sh --configuration Release --buildnumber $CI_PIPELINE_IID
        - dotnet nuget push Mjolnir*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json --no-symbols 1

debug:
    stage: test
    script:
        - ./build.sh

pages:
  stage: documentation
  only:
  - tags
  artifacts:
    paths:
    - public
  script:
  - ./build.sh --configuration Release --buildnumber $CI_PIPELINE_IID